/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsMicroledger = Microledger
export class Microledger {
  constructor(pk: string)
  preAnchorBlock(attachments: Array<string>, identifiers: Array<string>): string
  anchorBlock(block: string, signature: Buffer): string
  getBlocks(): Array<string>
}
